export const PRODUCT_SWAGGER_EXAMPLE = {
  id: 1,
  title: 'string',
  description: 'string',
  category: 'beauty',
  price: 1,
  discountPercentage: 1,
  rating: 1,
  stock: 1,
  tags: ['string', 'string'],
  brand: 'string',
  sku: 'string',
  weight: 1,
  dimensions: {
    width: 1,
    height: 1,
    depth: 1,
  },
  warrantyInformation: 'string',
  shippingInformation: 'string',
  availabilityStatus: 'In Stock',
  reviews: [
    {
      rating: 1,
      comment: 'string',
      date: 'string',
      reviewerName: 'string',
      reviewerEmail: 'string',
    },
  ],
  returnPolicy: 'string',
  minimumOrderQuantity: 1,
  meta: {
    createdAt: 'string',
    updatedAt: 'string',
    barcode: 'string',
    qrCode: 'string',
  },
  thumbnail: 'string',
  images: ['string'],
};
